### ISSUE TITLE
a few nitpicks

### ISSUE THREAD

**Issue by Fusion** [yvesago/glauth-ui-light#1]
Hi, this works really well!

I found these few issues while trying the tool:

1. When I try to create a new user, and it gets rejected due to eg. invalid characters, it seems to increment the "Pending registration" counter
2. When I edit+save a new user before clicking "Register" it also increments that counter
3. It looks like there is some confusion between "surname" and "givenname" (but the user is created correctly)
4. (An even more minor nit): After editing an existing user, committing the edit entails clicking "Register" which of course is not the correct verb in that scenario :)

Cheers

**Comment by yvesago** [comment]
Thanks for your tests and glauth ! it's really a cool stuff.

> Hi, this works really well!
> 
> I found these few issues while trying the tool:

Your nitpicks are really welcomed and and show the mistakes of UI 
 
>     1. When I try to create a new user, and it gets rejected due to eg. invalid characters, it seems to increment the "Pending registration" counter
> 
>     2. When I edit+save a new user before clicking "Register" it also increments that counter

This is more a create and update process. So I will change "Save" by "Update"

>     3. It looks like there is some confusion between "surname" and "givenname" (but the user is created correctly)

Absolutely :-/ nice catch

>     4. (An even more minor nit): After editing an existing user, committing the edit entails clicking "Register" which of course is not the correct verb in that scenario :)

I will change this by "Commit changes"

Soon in a next release

Feel free to add more advice
