### ISSUE TITLE
Early hints about failing password policy

### ISSUE THREAD

**Issue by Jonny007-MKD** [yvesago/glauth-ui-light#12]
It would be nice if you could give an hint early if the entered password is going to fail the policy, i.e. by using the HTML5 `pattern` attribute filled with `passpolicy.min` and `.max`.

https://github.com/yvesago/glauth-ui-light/blob/08e5512fe5b2858f5dca2423b0e11658fc89dcfa/routes/web/templates/user/edit.tmpl#L188

     <input ... pattern="*{3,16}" ... name="inputPassword" >

See live example here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

**Comment by Jonny007-MKD** [comment]
The same could be done at other places, e.g. when creating a group:

https://github.com/yvesago/glauth-ui-light/blob/08e5512fe5b2858f5dca2423b0e11658fc89dcfa/routes/web/templates/group/create.tmpl#L10

    <input ... pattern="[a-z]{2,16}" ... name="inputName">

**Comment by yvesago** [comment]
Thanks for this nice tips but the use of bootstrap need to put the full form with "was-validated" css class. This will create too much complexity on frontend.
